jobs:
    my_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: build and test
              uses: |
                   npm install
                   npm test